### ISSUE TITLE
JSIndexedPropertyAccessExpressionImpl Error

### ISSUE THREAD

**Issue by newtriks** [johnlindquist/open-source-plugins#4]
com.intellij.lang.javascript.psi.impl.JSIndexedPropertyAccessExpressionImpl cannot be cast to com.intellij.psi.PsiReference: com.intellij.lang.javascript.psi.impl.JSIndexedPropertyAccessExpressionImpl cannot be cast to com.intellij.psi.PsiReference
java.lang.ClassCastException: com.intellij.lang.javascript.psi.impl.JSIndexedPropertyAccessExpressionImpl cannot be cast to com.intellij.psi.PsiReference
    at org.robotlegs.toolwindows.Mappings.resolveElement(Mappings.java:102)
    at org.robotlegs.toolwindows.Mappings.getMappedElementsFromUsage(Mappings.java:81)
    at org.robotlegs.toolwindows.Mappings.getMappingByClassAndFunctionProject(Mappings.java:55)
    at org.robotlegs.toolwindows.BrowserToolWindowFactory.refreshValues(BrowserToolWindowFactory.java:98)
    at org.robotlegs.toolwindows.BrowserToolWindowFactory.createToolWindowContent(BrowserToolWindowFactory.java:87)
    at com.intellij.openapi.wm.impl.ToolWindowImpl.ensureContentInitialized(ToolWindowImpl.java:423)
    at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$10$1.run(ToolWindowManagerImpl.java:483)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:678)
    at java.awt.EventQueue.access$000(EventQueue.java:86)
    at java.awt.EventQueue$1.run(EventQueue.java:639)
    at java.awt.EventQueue$1.run(EventQueue.java:637)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:648)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:661)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:514)
    at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:410)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:368)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by johnlindquist** [comment]
Can you grab the latest and try again?
