### ISSUE TITLE
NullPointerException while trying to open Robotlegs plugin

### ISSUE THREAD

**Issue by vrobel** [johnlindquist/open-source-plugins#7]
null
java.lang.NullPointerException
    at org.robotlegs.toolwindows.BrowserToolWindowFactory.prepareTableData(BrowserToolWindowFactory.java:164)
    at org.robotlegs.toolwindows.BrowserToolWindowFactory.createTable(BrowserToolWindowFactory.java:109)
    at org.robotlegs.toolwindows.BrowserToolWindowFactory.refreshValues(BrowserToolWindowFactory.java:100)
    at org.robotlegs.toolwindows.BrowserToolWindowFactory.createToolWindowContent(BrowserToolWindowFactory.java:90)
    at com.intellij.openapi.wm.impl.ToolWindowImpl.ensureContentInitialized(ToolWindowImpl.java:430)
    at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$11$1.run(ToolWindowManagerImpl.java:493)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:333)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:641)
    at java.awt.EventQueue.access$000(EventQueue.java:84)
    at java.awt.EventQueue$1.run(EventQueue.java:602)
    at java.awt.EventQueue$1.run(EventQueue.java:600)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:611)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:683)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:534)
    at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:416)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:374)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by johnlindquist** [comment]
What version of Intellij are you using? And does this prevent the plugin from actually running?

**Comment by vrobel** [comment]
I keep forgetting that I'm using IDEA 11. And yes - Robotlegs window is empty.

**Comment by johnlindquist** [comment]
Ok, I'll starting testing against 11 soon. I don't know what may have changed yet. Thanks for letting me know.
