### ISSUE TITLE
QuickJump plugin PHPStorm

### ISSUE THREAD

**Issue by tlayh** [johnlindquist/open-source-plugins#8]
With the current EAP (110.359) the QuickJump plugin is not working anymore.

Working on Windows7 64bit
## Below the output from the error log:

Error during dispatching of java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=javax.swing.Timer$DoPostEvent@9a8194,notifier=null,catchExceptions=false,when=1321527500503] on sun.awt.windows.WToolkit@cc0e01
java.lang.AbstractMethodError
    at com.intellij.psi.impl.cache.impl.id.IdTableBuilding.scanWords(IdTableBuilding.java:416)
    at com.intellij.psi.impl.cache.impl.id.IdTableBuilding.scanWords(IdTableBuilding.java:379)
    at com.johnlindquist.quickjump.QuickJumpAction.calcWords(QuickJumpAction.java:649)
    at com.johnlindquist.quickjump.QuickJumpAction$SearchBox.findCamelCase(QuickJumpAction.java:415)
    at com.johnlindquist.quickjump.QuickJumpAction$SearchBox.access$800(QuickJumpAction.java:207)
    at com.johnlindquist.quickjump.QuickJumpAction$SearchBox$3$1.run(QuickJumpAction.java:356)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:842)
    at com.johnlindquist.quickjump.QuickJumpAction$SearchBox$3.actionPerformed(QuickJumpAction.java:346)
    at javax.swing.Timer.fireActionPerformed(Timer.java:291)
    at javax.swing.Timer$DoPostEvent.run(Timer.java:221)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:641)
    at java.awt.EventQueue.access$000(EventQueue.java:84)
    at java.awt.EventQueue$1.run(EventQueue.java:602)
    at java.awt.EventQueue$1.run(EventQueue.java:600)
    at java.security.AccessController.$$YJP$$doPrivileged(Native Method)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:611)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:686)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:534)
    at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:416)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:374)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

java.lang.AbstractMethodError
    at com.intellij.psi.impl.cache.impl.id.IdTableBuilding.scanWords(IdTableBuilding.java:416)
    at com.intellij.psi.impl.cache.impl.id.IdTableBuilding.scanWords(IdTableBuilding.java:379)
    at com.johnlindquist.quickjump.QuickJumpAction.calcWords(QuickJumpAction.java:649)
    at com.johnlindquist.quickjump.QuickJumpAction$SearchBox.findCamelCase(QuickJumpAction.java:415)
    at com.johnlindquist.quickjump.QuickJumpAction$SearchBox.access$800(QuickJumpAction.java:207)
    at com.johnlindquist.quickjump.QuickJumpAction$SearchBox$3$1.run(QuickJumpAction.java:356)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:842)
    at com.johnlindquist.quickjump.QuickJumpAction$SearchBox$3.actionPerformed(QuickJumpAction.java:346)
    at javax.swing.Timer.fireActionPerformed(Timer.java:291)
    at javax.swing.Timer$DoPostEvent.run(Timer.java:221)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:641)
    at java.awt.EventQueue.access$000(EventQueue.java:84)
    at java.awt.EventQueue$1.run(EventQueue.java:602)
    at java.awt.EventQueue$1.run(EventQueue.java:600)
    at java.security.AccessController.$$YJP$$doPrivileged(Native Method)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:611)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:686)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:534)
    at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:416)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:374)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

java.lang.AbstractMethodError
    at com.intellij.psi.impl.cache.impl.id.IdTableBuilding.scanWords(IdTableBuilding.java:416)
    at com.intellij.psi.impl.cache.impl.id.IdTableBuilding.scanWords(IdTableBuilding.java:379)
    at com.johnlindquist.quickjump.QuickJumpAction.calcWords(QuickJumpAction.java:649)
    at com.johnlindquist.quickjump.QuickJumpAction$SearchBox.findCamelCase(QuickJumpAction.java:415)
    at com.johnlindquist.quickjump.QuickJumpAction$SearchBox.access$800(QuickJumpAction.java:207)
    at com.johnlindquist.quickjump.QuickJumpAction$SearchBox$3$1.run(QuickJumpAction.java:356)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:842)
    at com.johnlindquist.quickjump.QuickJumpAction$SearchBox$3.actionPerformed(QuickJumpAction.java:346)
    at javax.swing.Timer.fireActionPerformed(Timer.java:291)
    at javax.swing.Timer$DoPostEvent.run(Timer.java:221)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:641)
    at java.awt.EventQueue.access$000(EventQueue.java:84)
    at java.awt.EventQueue$1.run(EventQueue.java:602)
    at java.awt.EventQueue$1.run(EventQueue.java:600)
    at java.security.AccessController.$$YJP$$doPrivileged(Native Method)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:611)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:686)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:534)
    at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:416)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:374)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by johnlindquist** [comment]
I just updated to fix the bug introduced by the latest EAP. Can you update and close this issue if it works for you?

**Comment by tlayh** [comment]
After the update to QuickJump 4.3 everything works fine again. Tested on EAP 110.437

Thanks for the very fast fix.
