### ISSUE TITLE
Quick Jump plugin PHPStorm

### ISSUE THREAD

**Issue by Annotator** [johnlindquist/open-source-plugins#9]
Installed your latest version (4.3) on my PHPStorm 111.19 (MAC) and I get this error:

Error during dispatching of java.awt.event.KeyEvent[KEY_PRESSED,keyCode=59,keyText=;,keyChar='ö',modifiers=⌘,extModifiers=⌘,keyLocation=KEY_LOCATION_STANDARD,rawCode=0,primaryLevelUnicode=0,scancode=0] on frame1: No such child: 0
java.lang.ArrayIndexOutOfBoundsException: No such child: 0
    at java.awt.Container.getComponent(Container.java:294)
    at com.intellij.ui.popup.AbstractPopup.isToDrawMacCorner(AbstractPopup.java:315)
    at com.intellij.ui.popup.AbstractPopup.init(AbstractPopup.java:205)
    at com.intellij.ui.popup.ComponentPopupBuilderImpl.createPopup(ComponentPopupBuilderImpl.java:207)
    at com.johnlindquist.quickjump.QuickJumpAction.actionPerformed(QuickJumpAction.java:89)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:534)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:582)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:450)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:198)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:520)
    at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:416)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:374)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by johnlindquist** [comment]
Unfortunately, it's a bug in PhpStorm 3.0 for Mac. It will be resolved in the next PhpStorm update (it was fixed before Intellij 11 was released). The next PhpStorm eap should be available in the next couple weeks.
